;;; SPDX-FileCopyrightText: 2026 BrokenShine <xchai404@gmail.com>
;;;
;;; SPDX-License-Identifier: GPL-3.0-only

(define-module (jeans packages nix-ld)
  #:use-module (guix packages)
  #:use-module (gnu packages gcc)
  #:use-module (gnu packages rust)
  #:use-module (guix build-system cargo)
  #:use-module (guix git-download)
  #:use-module (guix packages)
  #:use-module (guix utils)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (guix gexp)
  #:use-module (jeans packages rust-crates))

(define-public nix-ld
  (package
    (name "nix-ld")
    (version "2.0.6")
    (source
     (origin
       (method git-fetch)
       (uri (git-reference
             (url "https://github.com/nix-community/nix-ld")
             (commit (string-append version))))
       (file-name (git-file-name name version))
       (sha256
        (base32 "1d00pdxnrkpxfjd1dfrmc5i7yz30ijx1nkzh75n4799v5mdh9mr3"))))
    (build-system cargo-build-system)
    (arguments
     (list
      #:rust rust-1.88
      #:install-source? #f
      #:phases
      #~(modify-phases %standard-phases
          (add-after 'unpack 'strip-dev-deps
            (lambda _
              ;; Remove [[test]] section, [dev-dependencies] section, and tests/
              ;; — cargo --offline won't have rstest/tempfile vendored.
              ;; Cargo.toml layout:
              ;;   [[bin]] → [[test]] → [dependencies] → [build-dependencies]
              ;;   → [dev-dependencies] → [profile.dev] → ...
              ;; Delete [[test]] and its 'name' line, then delete
              ;; [dev-dependencies] and its 3 entry lines.
              (delete-file-recursively "tests")
              (invoke
               "sed" "-i"
               "-e" "/\\[\\[test\\]\\]/,+1d"
               "-e" "/\\[dev-dependencies\\]/,+3d"
               "Cargo.toml")))

          ;; Remove .cargo/config (generated by cargo-build-system) to
          ;; avoid conflict with upstream .cargo/config.toml.
          (add-after 'prepare-rust-crates 'remove-duplicate-cargo-config
            (lambda _
              (when (file-exists? ".cargo/config")
                (delete-file ".cargo/config"))))

          (add-before 'build 'set-env
            (lambda _
              ;; Enable unstable features (#![feature(lang_items)])
              (setenv "RUSTC_BOOTSTRAP" "1")
              ;; NIX_SYSTEM is used at compile time to determine
              ;; architecture-specific environment variable names.
              ;; Guix uses "x86_64-linux", nix-ld expects "x86_64_linux".
              (setenv "NIX_SYSTEM"
                      (string-map
                       (lambda (c) (if (char=? c #\-) #\_ c))
                       #$(%current-system)))))

          ;; Disable stack protector hardening — nolibc does not provide
          ;; __stack_chk_fail, causing link failures.
          (add-before 'build 'disable-stack-protector
            (lambda _
              (setenv "hardeningDisable"
                      (string-append (or (getenv "hardeningDisable") "")
                                     " stackprotector"))))
          (delete 'install)
          (add-after 'build 'install
            (lambda* (#:key outputs #:allow-other-keys)
              (let* ((out (assoc-ref outputs "out"))
                     (bin (string-append out "/bin"))
                     (libexec (string-append out "/libexec")))
                (mkdir-p bin)
                (mkdir-p libexec)
                (install-file "target/release/nix-ld" bin)
                ;; Provide libexec symlink for service activation
                (symlink (string-append bin "/nix-ld")
                         (string-append libexec "/nix-ld"))))))))
    (inputs (cargo-inputs 'nix-ld
                      #:module '(jeans packages rust-crates)))
    (home-page "https://github.com/nix-community/nix-ld")
    (synopsis "Run unpatched dynamic binaries on non-FHS systems")
    (description
     "nix-ld is a minimal ELF dynamic linker shim that allows pre-compiled
binaries to run on non-FHS systems like Guix System or NixOS.  It installs
at @file{/lib64/ld-linux-x86-64.so.2} and redirects to the actual Guix
glibc dynamic linker via the @code{NIX_LD} and @code{NIX_LD_LIBRARY_PATH}
environment variables.")
    (license license:lgpl2.1)))
